name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  core:
    name: Core Library Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Format check
      run: cargo fmt --all -- --check
    
    - name: Clippy check
      run: cargo clippy --all-targets --all-features -- -W clippy::all -A clippy::too_many_arguments
    
    - name: Library tests
      run: cargo test --lib
    
    - name: Golden tests (Required)
      run: cargo test --test golden_tests
    
    - name: Integration tests
      run: cargo test --test integration_tests
    
    - name: Build examples
      run: cargo build --examples
    
    - name: Test examples
      run: |
        mkdir -p artifacts
        cargo run --example dump -- tests/fixtures/simple.md > artifacts/simple_output.json
        cargo run --example dump -- tests/fixtures/branch.md > artifacts/branch_output.json
        echo "Examples executed successfully"
    
    - name: Upload dump artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dump-outputs
        path: artifacts/*.json
        retention-days: 7

  additional_tests:
    name: Additional Tests (Non-blocking)
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-additional-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Additional test suites
      run: |
        cargo test --test unit_engine_tests || echo "Unit engine tests failed (non-blocking)"
        cargo test --test clean_architecture_tests || echo "Clean architecture tests failed (non-blocking)"
        cargo test --test application_layer_tests || echo "Application layer tests failed (non-blocking)"
        cargo test --test dfs_scenario_tests || echo "DFS scenario tests failed (non-blocking)"
        cargo test --test unit_parser_tests || echo "Unit parser tests failed (non-blocking)"
        cargo test --test clean_architecture_contract_tests || echo "Contract tests failed (non-blocking)"
        cargo test --test ddd_separation_tests || echo "DDD separation tests failed (non-blocking)"
